# Generated by Django 5.0.4 on 2024-05-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languaje',
            new_name='language',
        ),
    ]
