# Generated by Django 5.0.4 on 2024-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('reggaeton', 'Reggaeton'), ('cumbia', 'Cumbia'), ('salsa', 'Salsa'), ('bachata', 'Bachata'), ('merengue', 'Merengue'), ('trap', 'Trap'), ('rap', 'Rap'), ('hip_hop', 'Hip Hop'), ('reggae', 'Reggae'), ('electronica', 'Electronica'), ('balada', 'Balada'), ('ranchera', 'Ranchera'), ('bolero', 'Bolero'), ('tango', 'Tango'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('metal', 'Metal'), ('punk', 'Punk'), ('indie', 'Indie'), ('alternativo', 'Alternativo'), ('clasica', 'Clasica'), ('country', 'Country'), ('disco', 'Disco'), ('ska', 'Ska'), ('soul', 'Soul'), ('funk', 'Funk'), ('r&b', 'R&B'), ('techno', 'Techno'), ('house', 'House'), ('dubstep', 'Dubstep'), ('trap', 'Trap')], max_length=20)),
                ('fichero', models.FileField(upload_to='canciones/')),
            ],
        ),
    ]
