# Generated by Django 5.0.4 on 2024-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='memasos/media/memes/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
