# Generated by Django 5.0.4 on 2024-05-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memasos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fk_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memasos.meme')),
            ],
        ),
    ]
