# Generated by Django 5.0.4 on 2024-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('foto_portada', models.ImageField(upload_to='falloucillo/media/portadas/')),
                ('foto_detalle', models.ImageField(upload_to='falloucillo/media/detalles/')),
            ],
        ),
    ]
