# Generated by Django 5.0.4 on 2024-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_disponible_alter_producto_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
