# Generated by Django 5.0.4 on 2024-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('estado', models.CharField(choices=[('nuevo', 'NUEVO'), ('usado', 'USADO')], max_length=200)),
                ('combustible', models.CharField(choices=[('gasolina', 'GASOLINA'), ('diesel', 'DIESEL')], max_length=8)),
                ('foto', models.FileField(upload_to='cochecitos/media/imagenes/')),
            ],
        ),
    ]
