# Generated by Django 5.0.4 on 2024-05-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
                ('foto', models.FileField(upload_to='directores/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('sinapsis', models.TextField()),
                ('fecha_rodaje', models.DateField()),
                ('fecha_estreno', models.DateField()),
                ('imagen', models.FileField(upload_to='peliculas/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinesa.director')),
            ],
        ),
    ]
