# Generated by Django 5.0.4 on 2024-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_manufacturer', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_price', models.IntegerField()),
                ('car_state', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado')], max_length=10)),
                ('car_fuel', models.CharField(choices=[('gasoil', 'Gasolina'), ('diesel', 'Diesel')], max_length=20)),
                ('car_photo', models.FileField(upload_to='images/')),
            ],
        ),
    ]
