# Generated by Django 5.0.4 on 2024-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], max_length=5)),
                ('combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel')], max_length=8)),
                ('foto', models.FileField(upload_to='coches/')),
            ],
        ),
    ]
