# Generated by Django 5.0.4 on 2024-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='frutaverdura')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_final', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
    ]
