# Generated by Django 5.0.4 on 2024-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completada', 'Completada')], max_length=20),
        ),
    ]
