# Generated by Django 5.0.4 on 2024-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.FloatField()),
                ('foto', models.FileField(upload_to='images/')),
            ],
        ),
    ]
