# Generated by Django 5.0.4 on 2024-06-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('numero_socios', models.IntegerField(blank=True, null=True)),
                ('fecha_apertura', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=70)),
                ('tipo', models.CharField(choices=[('WEED', 'Weed'), ('HASH', 'Hash'), ('EXTRACCION', 'Extraccion')], max_length=10)),
                ('concentracion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precio', models.IntegerField()),
                ('foto', models.FileField(upload_to='productos/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asocis.club')),
            ],
        ),
    ]
