# Generated by Django 5.0.4 on 2024-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
