# Generated by Django 5.0.4 on 2024-05-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenido', '0002_mantenimiento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='slug',
            field=models.SlugField(),
        ),
    ]
