# Generated by Django 5.0.4 on 2024-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenido', '0003_alter_mantenimiento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
